apiVersion: v1
kind: Service
metadata:
  name: students-create-service
spec:
  selector:
    app: students-create-service
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30081
      targetPort: 8081
  type: NodePort 